query GetQueryPosts($search: String = "", $tag: String = "", $first: Int = 100) {
  posts(first: $first, where: {search: $search, tag: $tag}) {
    nodes {
      date
      excerpt
      slug
      tags(first: 3) {
        nodes {
          name
          slug
        }
      }
      title
    }
  }
}

query GetSinglePost($id: ID = "") {
  post(id: $id, idType: SLUG) {
    date
    content
    title
    tags(first: 3) {
      nodes {
        name
        slug
        posts(first: 3) {
          nodes {
            date
            excerpt
            slug
            title
            tags(first: 3) {
              nodes {
                name
                slug
              }
            }
          }
        }
      }
    }
  }
}